
let userData =

[
    {
        "uID": 1,
        "firstname": "Neen",
        "lastname": "Sever",
        "username": "NeenS",
        "email": "null",
        "pronouns": "They/Him",
        "avatar": "https://www.pdx.edu/recreation/sites/g/files/znldhr2076/files/styles/event_detail_455x325_/public/2022-09/Queer%20Climb%20%281%29.jpg?h=0089d55f&itok=RYe4cuKZ",
        "bio": "No to v5 sharks",
        "location": "London",
        "level": "Intermediate",
        "top": 0,
        "gender": "Trans"
    },
    {
        "uID": 2,
        "firstname": "Beau",
        "lastname": "Crimpboy",
        "username": "Crimpboy",
        "email": "undefined",
        "pronouns": "He/His",
        "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYAOMF4SagiWjJH4so6P-7RrqRaVQnza0uJg&usqp=CAU",
        "bio": "Huzzaaah",
        "location": "London",
        "level": "Advanced",
        "top": 0,
        "gender": "Male"
    },
    {
        "uID": 3,
        "firstname": "Simon",
        "lastname": "The Rock",
        "username": "RockHopper",
        "email": "null",
        "pronouns": "He/His",
        "avatar": "https://climbinghouse.com/wp-content/uploads/2022/09/how_do_climbers_make_money-1024x692.jpg",
        "bio": "Professional intructor for +5 years. Looking for outdoor partner",
        "location": "Sheffield",
        "level": "Advanced",
        "top": 0,
        "gender": "Male"
    },
    {
        "uID": 5,
        "firstname": "Jon",
        "lastname": "Falkner",
        "username": "JFalkner",
        "email": "null",
        "pronouns": "He/His",
        "avatar": "http://media.wbur.org/wp/2017/02/unnamed-1000x667.jpg",
        "bio": "Looking to get back into climbing after a 5 year break",
        "location": "London",
        "level": "Beginner",
        "top": 1,
        "gender": "Male"
    },
    {
        "uID": 6,
        "firstname": "Simona",
        "lastname": "Hill",
        "username": "Simmi",
        "email": "null",
        "pronouns": "She/Her",
        "avatar": "https://media.istockphoto.com/id/480310380/photo/climber-woman-standing-in-front-of-a-stone-rock-outdoor.jpg?s=612x612&w=is&k=20&c=Hg3qLlohSh1QBzx8VktLc7jzSGXzPIk00i2eXpjQ4hQ=",
        "bio": "Mainly indoors, but looking to climb outside now summer approaches",
        "location": "London",
        "level": "Advanced",
        "top": 1,
        "gender": "Female"
    },
    {
        "uID": 7,
        "firstname": "Sarah",
        "lastname": "Evans",
        "username": "Rockmom",
        "email": "null",
        "pronouns": "She/Her",
        "avatar": "https://www.climbing.com/wp-content/uploads/2009/02/gracie_susan1_14148.jpg?width=375",
        "bio": "Mother of 3 children and fond climber",
        "location": "London",
        "level": "Advanced",
        "top": 1,
        "gender": "Female"
    },
    {
        "uID": 8,
        "firstname": "Lizzy",
        "lastname": "Tylecote",
        "username": "Lizzy",
        "email": "null",
        "pronouns": "She/Her",
        "avatar": "https://www.climbing.com/wp-content/uploads/2009/02/lynn-atd2-squamish_14196.jpg?width=730",
        "bio": "Looking to get into Trad",
        "location": "London",
        "level": "Advanced",
        "top": 1,
        "gender": "Female"
    },
    {
        "uID": 9,
        "firstname": "Suzie",
        "lastname": "Evrard",
        "username": "SuzieE",
        "email": "null",
        "pronouns": "She/Her",
        "avatar": "https://www.climbing.com/wp-content/uploads/2009/02/lynn-atd2-squamish_14196.jpg?width=730",
        "bio": "Just started climbing",
        "location": "London",
        "level": "Beginner",
        "top": 1,
        "gender": "Female"
    }
]